/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToastsRouteImport } from './routes/toasts'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as ModalsRouteImport } from './routes/modals'
import { Route as LoginScreensRouteImport } from './routes/login-screens'
import { Route as IndexRouteImport } from './routes/index'

const ToastsRoute = ToastsRouteImport.update({
  id: '/toasts',
  path: '/toasts',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalsRoute = ModalsRouteImport.update({
  id: '/modals',
  path: '/modals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginScreensRoute = LoginScreensRouteImport.update({
  id: '/login-screens',
  path: '/login-screens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login-screens': typeof LoginScreensRoute
  '/modals': typeof ModalsRoute
  '/navigation': typeof NavigationRoute
  '/toasts': typeof ToastsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-screens': typeof LoginScreensRoute
  '/modals': typeof ModalsRoute
  '/navigation': typeof NavigationRoute
  '/toasts': typeof ToastsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login-screens': typeof LoginScreensRoute
  '/modals': typeof ModalsRoute
  '/navigation': typeof NavigationRoute
  '/toasts': typeof ToastsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login-screens' | '/modals' | '/navigation' | '/toasts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login-screens' | '/modals' | '/navigation' | '/toasts'
  id:
    | '__root__'
    | '/'
    | '/login-screens'
    | '/modals'
    | '/navigation'
    | '/toasts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginScreensRoute: typeof LoginScreensRoute
  ModalsRoute: typeof ModalsRoute
  NavigationRoute: typeof NavigationRoute
  ToastsRoute: typeof ToastsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toasts': {
      id: '/toasts'
      path: '/toasts'
      fullPath: '/toasts'
      preLoaderRoute: typeof ToastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modals': {
      id: '/modals'
      path: '/modals'
      fullPath: '/modals'
      preLoaderRoute: typeof ModalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-screens': {
      id: '/login-screens'
      path: '/login-screens'
      fullPath: '/login-screens'
      preLoaderRoute: typeof LoginScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginScreensRoute: LoginScreensRoute,
  ModalsRoute: ModalsRoute,
  NavigationRoute: NavigationRoute,
  ToastsRoute: ToastsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
