/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadersRouteImport } from './routes/uploaders'
import { Route as TooltipsRouteImport } from './routes/tooltips'
import { Route as ToastsRouteImport } from './routes/toasts'
import { Route as TextareasRouteImport } from './routes/textareas'
import { Route as TabsRouteImport } from './routes/tabs'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SwitchesRouteImport } from './routes/switches'
import { Route as SlidersRouteImport } from './routes/sliders'
import { Route as SelectsRouteImport } from './routes/selects'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RadiosRouteImport } from './routes/radios'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PaginationRouteImport } from './routes/pagination'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as ModalsRouteImport } from './routes/modals'
import { Route as LoginScreensRouteImport } from './routes/login-screens'
import { Route as LoadersRouteImport } from './routes/loaders'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as InputsRouteImport } from './routes/inputs'
import { Route as GridRouteImport } from './routes/grid'
import { Route as FormValidationRouteImport } from './routes/form-validation'
import { Route as FlexRouteImport } from './routes/flex'
import { Route as DropdownsRouteImport } from './routes/dropdowns'
import { Route as DrawersRouteImport } from './routes/drawers'
import { Route as DividersRouteImport } from './routes/dividers'
import { Route as DatepickerRouteImport } from './routes/datepicker'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as CheckboxesRouteImport } from './routes/checkboxes'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as ButtonsRouteImport } from './routes/buttons'
import { Route as BreadcrumbsRouteImport } from './routes/breadcrumbs'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AccordionsRouteImport } from './routes/accordions'
import { Route as IndexRouteImport } from './routes/index'

const UploadersRoute = UploadersRouteImport.update({
  id: '/uploaders',
  path: '/uploaders',
  getParentRoute: () => rootRouteImport,
} as any)
const TooltipsRoute = TooltipsRouteImport.update({
  id: '/tooltips',
  path: '/tooltips',
  getParentRoute: () => rootRouteImport,
} as any)
const ToastsRoute = ToastsRouteImport.update({
  id: '/toasts',
  path: '/toasts',
  getParentRoute: () => rootRouteImport,
} as any)
const TextareasRoute = TextareasRouteImport.update({
  id: '/textareas',
  path: '/textareas',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchesRoute = SwitchesRouteImport.update({
  id: '/switches',
  path: '/switches',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidersRoute = SlidersRouteImport.update({
  id: '/sliders',
  path: '/sliders',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectsRoute = SelectsRouteImport.update({
  id: '/selects',
  path: '/selects',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiosRoute = RadiosRouteImport.update({
  id: '/radios',
  path: '/radios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginationRoute = PaginationRouteImport.update({
  id: '/pagination',
  path: '/pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalsRoute = ModalsRouteImport.update({
  id: '/modals',
  path: '/modals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginScreensRoute = LoginScreensRouteImport.update({
  id: '/login-screens',
  path: '/login-screens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadersRoute = LoadersRouteImport.update({
  id: '/loaders',
  path: '/loaders',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const InputsRoute = InputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const FormValidationRoute = FormValidationRouteImport.update({
  id: '/form-validation',
  path: '/form-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const FlexRoute = FlexRouteImport.update({
  id: '/flex',
  path: '/flex',
  getParentRoute: () => rootRouteImport,
} as any)
const DropdownsRoute = DropdownsRouteImport.update({
  id: '/dropdowns',
  path: '/dropdowns',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawersRoute = DrawersRouteImport.update({
  id: '/drawers',
  path: '/drawers',
  getParentRoute: () => rootRouteImport,
} as any)
const DividersRoute = DividersRouteImport.update({
  id: '/dividers',
  path: '/dividers',
  getParentRoute: () => rootRouteImport,
} as any)
const DatepickerRoute = DatepickerRouteImport.update({
  id: '/datepicker',
  path: '/datepicker',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckboxesRoute = CheckboxesRouteImport.update({
  id: '/checkboxes',
  path: '/checkboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonsRoute = ButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => rootRouteImport,
} as any)
const BreadcrumbsRoute = BreadcrumbsRouteImport.update({
  id: '/breadcrumbs',
  path: '/breadcrumbs',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionsRoute = AccordionsRouteImport.update({
  id: '/accordions',
  path: '/accordions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accordions': typeof AccordionsRoute
  '/alerts': typeof AlertsRoute
  '/breadcrumbs': typeof BreadcrumbsRoute
  '/buttons': typeof ButtonsRoute
  '/cards': typeof CardsRoute
  '/checkboxes': typeof CheckboxesRoute
  '/containers': typeof ContainersRoute
  '/datepicker': typeof DatepickerRoute
  '/dividers': typeof DividersRoute
  '/drawers': typeof DrawersRoute
  '/dropdowns': typeof DropdownsRoute
  '/flex': typeof FlexRoute
  '/form-validation': typeof FormValidationRoute
  '/grid': typeof GridRoute
  '/inputs': typeof InputsRoute
  '/lists': typeof ListsRoute
  '/loaders': typeof LoadersRoute
  '/login-screens': typeof LoginScreensRoute
  '/modals': typeof ModalsRoute
  '/navigation': typeof NavigationRoute
  '/pagination': typeof PaginationRoute
  '/progress': typeof ProgressRoute
  '/radios': typeof RadiosRoute
  '/search': typeof SearchRoute
  '/selects': typeof SelectsRoute
  '/sliders': typeof SlidersRoute
  '/switches': typeof SwitchesRoute
  '/tables': typeof TablesRoute
  '/tabs': typeof TabsRoute
  '/textareas': typeof TextareasRoute
  '/toasts': typeof ToastsRoute
  '/tooltips': typeof TooltipsRoute
  '/uploaders': typeof UploadersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accordions': typeof AccordionsRoute
  '/alerts': typeof AlertsRoute
  '/breadcrumbs': typeof BreadcrumbsRoute
  '/buttons': typeof ButtonsRoute
  '/cards': typeof CardsRoute
  '/checkboxes': typeof CheckboxesRoute
  '/containers': typeof ContainersRoute
  '/datepicker': typeof DatepickerRoute
  '/dividers': typeof DividersRoute
  '/drawers': typeof DrawersRoute
  '/dropdowns': typeof DropdownsRoute
  '/flex': typeof FlexRoute
  '/form-validation': typeof FormValidationRoute
  '/grid': typeof GridRoute
  '/inputs': typeof InputsRoute
  '/lists': typeof ListsRoute
  '/loaders': typeof LoadersRoute
  '/login-screens': typeof LoginScreensRoute
  '/modals': typeof ModalsRoute
  '/navigation': typeof NavigationRoute
  '/pagination': typeof PaginationRoute
  '/progress': typeof ProgressRoute
  '/radios': typeof RadiosRoute
  '/search': typeof SearchRoute
  '/selects': typeof SelectsRoute
  '/sliders': typeof SlidersRoute
  '/switches': typeof SwitchesRoute
  '/tables': typeof TablesRoute
  '/tabs': typeof TabsRoute
  '/textareas': typeof TextareasRoute
  '/toasts': typeof ToastsRoute
  '/tooltips': typeof TooltipsRoute
  '/uploaders': typeof UploadersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accordions': typeof AccordionsRoute
  '/alerts': typeof AlertsRoute
  '/breadcrumbs': typeof BreadcrumbsRoute
  '/buttons': typeof ButtonsRoute
  '/cards': typeof CardsRoute
  '/checkboxes': typeof CheckboxesRoute
  '/containers': typeof ContainersRoute
  '/datepicker': typeof DatepickerRoute
  '/dividers': typeof DividersRoute
  '/drawers': typeof DrawersRoute
  '/dropdowns': typeof DropdownsRoute
  '/flex': typeof FlexRoute
  '/form-validation': typeof FormValidationRoute
  '/grid': typeof GridRoute
  '/inputs': typeof InputsRoute
  '/lists': typeof ListsRoute
  '/loaders': typeof LoadersRoute
  '/login-screens': typeof LoginScreensRoute
  '/modals': typeof ModalsRoute
  '/navigation': typeof NavigationRoute
  '/pagination': typeof PaginationRoute
  '/progress': typeof ProgressRoute
  '/radios': typeof RadiosRoute
  '/search': typeof SearchRoute
  '/selects': typeof SelectsRoute
  '/sliders': typeof SlidersRoute
  '/switches': typeof SwitchesRoute
  '/tables': typeof TablesRoute
  '/tabs': typeof TabsRoute
  '/textareas': typeof TextareasRoute
  '/toasts': typeof ToastsRoute
  '/tooltips': typeof TooltipsRoute
  '/uploaders': typeof UploadersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accordions'
    | '/alerts'
    | '/breadcrumbs'
    | '/buttons'
    | '/cards'
    | '/checkboxes'
    | '/containers'
    | '/datepicker'
    | '/dividers'
    | '/drawers'
    | '/dropdowns'
    | '/flex'
    | '/form-validation'
    | '/grid'
    | '/inputs'
    | '/lists'
    | '/loaders'
    | '/login-screens'
    | '/modals'
    | '/navigation'
    | '/pagination'
    | '/progress'
    | '/radios'
    | '/search'
    | '/selects'
    | '/sliders'
    | '/switches'
    | '/tables'
    | '/tabs'
    | '/textareas'
    | '/toasts'
    | '/tooltips'
    | '/uploaders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accordions'
    | '/alerts'
    | '/breadcrumbs'
    | '/buttons'
    | '/cards'
    | '/checkboxes'
    | '/containers'
    | '/datepicker'
    | '/dividers'
    | '/drawers'
    | '/dropdowns'
    | '/flex'
    | '/form-validation'
    | '/grid'
    | '/inputs'
    | '/lists'
    | '/loaders'
    | '/login-screens'
    | '/modals'
    | '/navigation'
    | '/pagination'
    | '/progress'
    | '/radios'
    | '/search'
    | '/selects'
    | '/sliders'
    | '/switches'
    | '/tables'
    | '/tabs'
    | '/textareas'
    | '/toasts'
    | '/tooltips'
    | '/uploaders'
  id:
    | '__root__'
    | '/'
    | '/accordions'
    | '/alerts'
    | '/breadcrumbs'
    | '/buttons'
    | '/cards'
    | '/checkboxes'
    | '/containers'
    | '/datepicker'
    | '/dividers'
    | '/drawers'
    | '/dropdowns'
    | '/flex'
    | '/form-validation'
    | '/grid'
    | '/inputs'
    | '/lists'
    | '/loaders'
    | '/login-screens'
    | '/modals'
    | '/navigation'
    | '/pagination'
    | '/progress'
    | '/radios'
    | '/search'
    | '/selects'
    | '/sliders'
    | '/switches'
    | '/tables'
    | '/tabs'
    | '/textareas'
    | '/toasts'
    | '/tooltips'
    | '/uploaders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordionsRoute: typeof AccordionsRoute
  AlertsRoute: typeof AlertsRoute
  BreadcrumbsRoute: typeof BreadcrumbsRoute
  ButtonsRoute: typeof ButtonsRoute
  CardsRoute: typeof CardsRoute
  CheckboxesRoute: typeof CheckboxesRoute
  ContainersRoute: typeof ContainersRoute
  DatepickerRoute: typeof DatepickerRoute
  DividersRoute: typeof DividersRoute
  DrawersRoute: typeof DrawersRoute
  DropdownsRoute: typeof DropdownsRoute
  FlexRoute: typeof FlexRoute
  FormValidationRoute: typeof FormValidationRoute
  GridRoute: typeof GridRoute
  InputsRoute: typeof InputsRoute
  ListsRoute: typeof ListsRoute
  LoadersRoute: typeof LoadersRoute
  LoginScreensRoute: typeof LoginScreensRoute
  ModalsRoute: typeof ModalsRoute
  NavigationRoute: typeof NavigationRoute
  PaginationRoute: typeof PaginationRoute
  ProgressRoute: typeof ProgressRoute
  RadiosRoute: typeof RadiosRoute
  SearchRoute: typeof SearchRoute
  SelectsRoute: typeof SelectsRoute
  SlidersRoute: typeof SlidersRoute
  SwitchesRoute: typeof SwitchesRoute
  TablesRoute: typeof TablesRoute
  TabsRoute: typeof TabsRoute
  TextareasRoute: typeof TextareasRoute
  ToastsRoute: typeof ToastsRoute
  TooltipsRoute: typeof TooltipsRoute
  UploadersRoute: typeof UploadersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploaders': {
      id: '/uploaders'
      path: '/uploaders'
      fullPath: '/uploaders'
      preLoaderRoute: typeof UploadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooltips': {
      id: '/tooltips'
      path: '/tooltips'
      fullPath: '/tooltips'
      preLoaderRoute: typeof TooltipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toasts': {
      id: '/toasts'
      path: '/toasts'
      fullPath: '/toasts'
      preLoaderRoute: typeof ToastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textareas': {
      id: '/textareas'
      path: '/textareas'
      fullPath: '/textareas'
      preLoaderRoute: typeof TextareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs': {
      id: '/tabs'
      path: '/tabs'
      fullPath: '/tabs'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switches': {
      id: '/switches'
      path: '/switches'
      fullPath: '/switches'
      preLoaderRoute: typeof SwitchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sliders': {
      id: '/sliders'
      path: '/sliders'
      fullPath: '/sliders'
      preLoaderRoute: typeof SlidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selects': {
      id: '/selects'
      path: '/selects'
      fullPath: '/selects'
      preLoaderRoute: typeof SelectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radios': {
      id: '/radios'
      path: '/radios'
      fullPath: '/radios'
      preLoaderRoute: typeof RadiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagination': {
      id: '/pagination'
      path: '/pagination'
      fullPath: '/pagination'
      preLoaderRoute: typeof PaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modals': {
      id: '/modals'
      path: '/modals'
      fullPath: '/modals'
      preLoaderRoute: typeof ModalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-screens': {
      id: '/login-screens'
      path: '/login-screens'
      fullPath: '/login-screens'
      preLoaderRoute: typeof LoginScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loaders': {
      id: '/loaders'
      path: '/loaders'
      fullPath: '/loaders'
      preLoaderRoute: typeof LoadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputs': {
      id: '/inputs'
      path: '/inputs'
      fullPath: '/inputs'
      preLoaderRoute: typeof InputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-validation': {
      id: '/form-validation'
      path: '/form-validation'
      fullPath: '/form-validation'
      preLoaderRoute: typeof FormValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flex': {
      id: '/flex'
      path: '/flex'
      fullPath: '/flex'
      preLoaderRoute: typeof FlexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropdowns': {
      id: '/dropdowns'
      path: '/dropdowns'
      fullPath: '/dropdowns'
      preLoaderRoute: typeof DropdownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawers': {
      id: '/drawers'
      path: '/drawers'
      fullPath: '/drawers'
      preLoaderRoute: typeof DrawersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividers': {
      id: '/dividers'
      path: '/dividers'
      fullPath: '/dividers'
      preLoaderRoute: typeof DividersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datepicker': {
      id: '/datepicker'
      path: '/datepicker'
      fullPath: '/datepicker'
      preLoaderRoute: typeof DatepickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkboxes': {
      id: '/checkboxes'
      path: '/checkboxes'
      fullPath: '/checkboxes'
      preLoaderRoute: typeof CheckboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttons': {
      id: '/buttons'
      path: '/buttons'
      fullPath: '/buttons'
      preLoaderRoute: typeof ButtonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breadcrumbs': {
      id: '/breadcrumbs'
      path: '/breadcrumbs'
      fullPath: '/breadcrumbs'
      preLoaderRoute: typeof BreadcrumbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accordions': {
      id: '/accordions'
      path: '/accordions'
      fullPath: '/accordions'
      preLoaderRoute: typeof AccordionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordionsRoute: AccordionsRoute,
  AlertsRoute: AlertsRoute,
  BreadcrumbsRoute: BreadcrumbsRoute,
  ButtonsRoute: ButtonsRoute,
  CardsRoute: CardsRoute,
  CheckboxesRoute: CheckboxesRoute,
  ContainersRoute: ContainersRoute,
  DatepickerRoute: DatepickerRoute,
  DividersRoute: DividersRoute,
  DrawersRoute: DrawersRoute,
  DropdownsRoute: DropdownsRoute,
  FlexRoute: FlexRoute,
  FormValidationRoute: FormValidationRoute,
  GridRoute: GridRoute,
  InputsRoute: InputsRoute,
  ListsRoute: ListsRoute,
  LoadersRoute: LoadersRoute,
  LoginScreensRoute: LoginScreensRoute,
  ModalsRoute: ModalsRoute,
  NavigationRoute: NavigationRoute,
  PaginationRoute: PaginationRoute,
  ProgressRoute: ProgressRoute,
  RadiosRoute: RadiosRoute,
  SearchRoute: SearchRoute,
  SelectsRoute: SelectsRoute,
  SlidersRoute: SlidersRoute,
  SwitchesRoute: SwitchesRoute,
  TablesRoute: TablesRoute,
  TabsRoute: TabsRoute,
  TextareasRoute: TextareasRoute,
  ToastsRoute: ToastsRoute,
  TooltipsRoute: TooltipsRoute,
  UploadersRoute: UploadersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
